"""empty message

Revision ID: 158c40563e34
Revises: cc058d58c71
Create Date: 2013-11-10 01:51:30.234649

"""

# revision identifiers, used by Alembic.
revision = '158c40563e34'
down_revision = 'cc058d58c71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
