"""empty message

Revision ID: 10ac36852c1b
Revises: None
Create Date: 2014-03-13 20:14:05.146339

"""

# revision identifiers, used by Alembic.
revision = '10ac36852c1b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('master_code', sa.String(length=64), nullable=True),
    sa.Column('guest_code', sa.String(length=64), nullable=True),
    sa.Column('timer_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_code'),
    sa.UniqueConstraint('master_code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    op.drop_table('user')
    ### end Alembic commands ###
