"""empty message

Revision ID: 42b2077fa686
Revises: 5112e72483fb
Create Date: 2014-03-13 22:05:35.970126

"""

# revision identifiers, used by Alembic.
revision = '42b2077fa686'
down_revision = '5112e72483fb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', u'master_code')
    op.drop_column('timer', u'guest_code')
    op.alter_column('timer_code', 'code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('timer_code', 'code_type',
               existing_type=mysql.ENUM(u'master', u'guest'),
               nullable=False)
    op.alter_column('timer_code', 'timer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timer_code', 'timer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('timer_code', 'code_type',
               existing_type=mysql.ENUM(u'master', u'guest'),
               nullable=True)
    op.alter_column('timer_code', 'code',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.add_column('timer', sa.Column(u'guest_code', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('timer', sa.Column(u'master_code', mysql.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
